conda-env.yml


name: capturestudio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyside6>=6.5.0
  - gstreamer>=1.20
  - gst-plugins-base>=1.20
  - gst-plugins-good>=1.20
  - pygobject>=3.44.0
  - pip>=23.2
  - pip:
    # Testing
    - pytest>=7.4.0
    - pytest-qt>=4.2.0
    - pytest-cov>=4.1.0
    - pytest-mock>=3.11.1
    - pytest-benchmark>=4.0.0
    - pytest-timeout>=2.1.0
    - pytest-xdist>=3.3.1
    
    # Type checking
    - mypy>=1.5.0
    - types-setuptools>=68.0.0
    
    # Code quality
    - black>=23.7.0
    - pylint>=2.17.5
    - isort>=5.12.0
    - flake8>=6.1.0
    - flake8-bugbear>=23.7.10
    - bandit>=1.7.5
    
    # Documentation
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=1.3.0
    - sphinx-autodoc-typehints>=1.24.0
    - sphinx-copybutton>=0.5.2
    - sphinx-design>=0.5.0
    
    # Development
    - debugpy>=1.6.7
    - memory_profiler>=0.61.0
    - line_profiler>=4.1.1
    - python-dotenv>=1.0.0
    - loguru>=0.7.0
    
    # Build tools
    - pyinstaller>=5.13.0
    - build>=1.0.3
    - twine>=4.0.2
    - check-manifest>=0.49
    - bump2version>=1.0.1
    
    # Git hooks
    - pre-commit>=3.3.3
    - commitizen>=3.6.0